---
- name: determine uname kurnel release
  command: uname -r
  register: _uname_kurnel_release
  changed_when: False

- name: install recommended extra packages
  become: True
  apt:
    name: "{{item}}"
    state: present
    # install_recommends: True
  with_items:
  - curl
  - linux-image-extra-{{_uname_kurnel_release.stdout}}
  - linux-image-extra-virtual
  - apt-transport-https
  - ca-certificates

- name: add docker apt key
  become: True
  apt_key:
    data: "{{ lookup('file', '../files/docker-apt-key') }}"
    state: present

- name: gather facts to have access to ansible_distribution_release
  setup:

- name: add docker apt repository
  become: True
  apt_repository:
    repo: deb https://apt.dockerproject.org/repo/ ubuntu-{{ansible_distribution_release}} main
    update_cache: True

- name: install docker engine
  become: True
  apt:
    name: docker-engine={{docker_version}}

- name: add {{item}} to docker group
  become: True
  user:
    name: "{{item}}"
    groups: docker
    append: True
  with_items: "{{docker_users}}"
  when: docker_users is defined

- name: create the docker systemd directory
  become: True
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
