---
- name: install recommended extra packages
  become: True
  apt:
    name: "{{item}}"
    state: present
  with_items:
  - curl
  - apt-transport-https
  - ca-certificates

- name: add docker apt key
  become: True
  apt_key:
    data: "{{ lookup('file', '../files/docker-apt-key') }}"
    state: present

- name: gather facts to have access to ansible_distribution_release
  setup:
  when: ansible_distribution_release is undefined

- name: add docker apt repository
  become: True
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
    update_cache: True

- name: find available docker-ce versions
  raw: apt-cache madison docker-ce | awk '{print $3}'
  register: _docker_versions
  changed_when: false

- name: error out if the docker_version is not valid
  fail:
    msg: "The specified docker_version: '{{docker_version}}' is not valid! Allowed docker versions are [{{_docker_versions.stdout_lines | join(', ')}}]"
  when: docker_version not in _docker_versions.stdout_lines

- name: install docker comunity edition
  become: True
  apt:
    name: docker-ce={{docker_version}}

- name: add {{item}} to docker group
  become: True
  user:
    name: "{{item}}"
    groups: docker
    append: True
  with_items: "{{docker_users}}"
  when: docker_users is defined

- name: create the docker systemd directory
  become: True
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
