- name: determine uname kurnel release
  command: uname -r
  register: _uname_kurnel_release
  changed_when: False

- name: install recommended recommended extra packages
  apt:
    name: "{{item}}"
    state: present
  with_items:
  - curl
  - linux-image-extra-{{_uname_kurnel_release.stdout}}
  - linux-image-extra-virtual
  - apt-transport-https
  - ca-certificates

- name: add docker apt key
  apt_key:
    data: "{{ lookup('file', '../files/docker-apt-key') }}"
    state: present

- name: gather facts to have access to ansible_distribution_release
  setup:

- name: add docker apt repository
  apt_repository:
    repo: deb https://apt.dockerproject.org/repo/ ubuntu-{{ansible_distribution_release}} main
    update_cache: yes

- name: install docker engine
  apt:
    name: docker-engine={{docker_version}}

- name: add {{item}} to docker group
  user:
    name: "{{item}}"
    groups: docker
    append: yes
  with_items: "{{docker_users}}"
  when: docker_users is defined
